### PR TITLE
docker: Add initial Dockerfile

### PR DESCRIPTION
**Pull request by kallisti5**

### CODE REVIEW

**Comment by kallisti5** [comment]
I'm not 100% sure how to properly "compile" the haikudepotserver and spawn it... however this is a start to containerizing it.

The "RUN" items are performed when generating the image (compile binaries, etc).   The "CMD" parts are starting the application.

**Comment by kallisti5** [comment]
Modified with some tweaks after your email comments. The container stuff can live next to the rpm stuff without much interaction between the two. One the container is working, we can automate building it into a container from your repo via hub.docker.com.

As an example, our nginx router container automatically builds when commits are made to the repository:
https://hub.docker.com/r/haiku/nginx-router/

**Comment by aplgithub** [comment]
Hello;

I am not confident all the issues have been considered here.  I don't think it makes sense to use the Docker image for build as well as deployment.  Usually the build products get created and then a deployment docker image is created from that.  I can stop making RPMs and instead deploy the "war" files to [github releases](https://help.github.com/articles/distributing-large-binaries/) or something like that.  It may be easier.
[hds-docker-rough-ideas.pdf](https://github.com/aplgithub/haikudepotserver/files/1385823/hds-docker-rough-ideas.pdf)


I have attached a PDF illustrating rough thoughts on what might be required, but there are some issues.

For example, where does config live (it's not in the RPM today for example - I edit it by hand) and how does it get into the Docker image?  Where does the logging come out, how does logging get stored and where can I see the logging?  'hvif2png' is a tool I made that is in the Haiku source and I need a build of this able to be executed by the application-server in the Docker image as well.  Does there need to be another docker container for [Postgres](https://www.postgresql.org/)?  Where is the database storage?  How does the database get backed-up?  How can I access this database remotely for admin?  How does the front-end load-balancer Docker image get configured?

I think it would be worth making time for a voice call to talk this over.

Regards;

**Comment by aplgithub** [comment]
Hi @kallisti5 - just wondering as well; what other systems are in the Haiku server-side environment with SQL databases attached?

**Comment by kallisti5** [comment]
So far, the infrastructure hasn't needed any database servers. (i'm just using the internal h2 database for gerrit)

A map of what has been configured + deployed so far is here:
https://github.com/haiku/infrastructure/blob/master/docker-compose.yaml

"Ideal" Docker containers follow the following design:
   * One "master" process.  In this case java or a launcher script for java.
   * All logs to stdout from the master process or a child of the master
   * configuration directives like database URI'S configured via environment variables the master process consumes.
   * Initial database creation / seeding done automatically at boot when needed.
   * All additional application requirements are external resources.
   * All persistent on-disk databases/caches/documents/assets in as few locations as possible.

In our environment, it is handy to expose all web services via a master http reverse proxy. This lets us handle all vhost stuff in a central place.

**Comment by aplgithub** [comment]
> So far, the infrastructure hasn't needed any database servers.

Would it be possible to use an [off-the-shelf](https://github.com/docker-library/postgres/blob/1805adb0693d9602bfb19b6bf2583b311c43b749/10/alpine/Dockerfile) docker setup for PG with storage on a mounted volume and then use "pg_dump" to pull backups off?

> All logs to stdout from the master process or a child of the master

Is there a log-viewer or access to a platform where those logs are situated so that I can see them?

> configuration directives like database URI'S configured via environment variables...

How does the database password, for example, get configured?

> Initial database creation / seeding done automatically at boot when needed.

The database and user for HDS should be initialized by hand noting that the database storage is persistent and not transient.  The actual schema objects are then created by the application as it starts.

> All additional application requirements are external resources.

Can you clarify what you mean by this?

> All persistent on-disk databases/caches/documents/assets in as few locations as possible.

In the case of HDS, this is just the database.

**Comment by aplgithub** [comment]
I will see if I can get the HDS part working in Docker in the meantime.

**Comment by aplgithub** [comment]
Actually it needs an SMTP relay as well; this is for signup and forgot-my-password.

**Comment by kallisti5** [comment]
for the SMTP relay, we already have one available in our maui container deployment.  Simply connect to "smtp:25" and send your mail :-)  (smtp is the hostname)

**Comment by kallisti5** [comment]
1) Off the shelf postgresql isn't a big deal and should be pretty easy.

2) docker logs <containerid>   is how you normally view the stdout container logs.

3) docker 1.13+ offers an internal password store, but 1.12 (which is what we're running, doesn't)
    Here is a common solution:   https://stackoverflow.com/questions/22651647/docker-and-securing-passwords#31756244

4) "All additional application requirements are external resources."   Using smtp as an example, we offer an open smtp relay internally to our docker containers.

**Comment by aplgithub** [comment]
Did you get my message in email about the Docker image being created for HDS?

**Comment by kallisti5** [comment]
Hey! What's the status on this?    I'm not 100% sure what needs be done to this pull request to get it in (and I don't see any docker-related stuff checked in)

**Comment by aplgithub** [comment]
We had an offline  email exchange in early December 2017 around my own approach to get this working.  The last email is from 6th December 2017 and is titled "Re: HDS Docker".  Can you please see if you still have that and see what your thoughts are on the approach taken there.

**Comment by kallisti5** [comment]
Right, I don't fully understand why I was sent a tgz file.  Will the dockerfile not live with the code it containerizes?

**Comment by aplgithub** [comment]
I guess the containerization process is not clear to me.  My thinking is that the build products (native binary and java binary) are produced and are *afterwards* bundled into a Docker container.  I guess you're thinking instead that the build process will generate a Docker image?  I have found [this](https://github.com/spotify/dockerfile-maven) maven plugin which will allow the maven build process to generate Docker images so perhaps I can make that work.  Can you look at the tar-ball anyway to understand roughly what I am intending to do?

**Comment by kallisti5** [comment]
Ok, it can go either way. Generally, projects will "own" the code to put their app into a container (and keep it in their git repo) since at the end of the day, the app developer has a complete picture of the environmental requirements.  If you need to add dependencies, you can do so.

However, we could consider you "container hostile" (i'm 99% joking with that term) and build your containers from our [infrastructure](https://github.com/haiku/infrastructure/tree/master/docker) repo. You wouldn't need to really interact with the container building code any, but would need to let the infrastructure team know if your requirements change.

**Comment by aplgithub** [comment]
Hi @kallisti5; did you get my message regarding this on the HDS mailing list?

**Comment by kallisti5** [comment]
yeah! Sorry for the delay. Lots going on. I'll get to it over the next few days.

**Comment by aplgithub** [comment]
Hi Alex; ideally, I would adjust the release script so that when I create a release, the script would modify the Dockerfile with the correct versions of the dependencies required to run (jetty / pg-driver / war).  The modified Dockerfile would be stored at the release tag in the HDS repository.  Your end would checkout the repository at that tag and then run the Dockerfile which will already know which versions of everything it requires to run.  So the Dockerfile you need to use lives in the HDS repository at a specific tag.  Does that sound OK?

**Comment by aplgithub** [comment]
The Docker branch is now merged; see mailing list.  I will close this PR as it is now redundant.  We can discuss further on the mailing list and new issues can be raised on here to sort out specific problems.

**Pull request closed without merging**
